# Generated by Django 5.0.7 on 2024-07-14 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fly_ash", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tanah_putih", models.DecimalField(decimal_places=2, max_digits=5)),
                ("naoh", models.DecimalField(decimal_places=2, max_digits=5)),
                ("air", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pasir", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="CalculationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compressive_strength",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "tensile_strength",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("porosity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("density", models.DecimalField(decimal_places=2, max_digits=8)),
                ("absorption", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "material_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mortar_calc.materialdata",
                    ),
                ),
            ],
        ),
    ]
